name: Advanced Usage

on: push


jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        files: [README.md]
        
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
        
      - uses: docker://pandoc/latex:2.9 
        with:
          args: --output=output/output.html  -t html -f markdown  ${{ matrix.files }}

  
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
              
       
