name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - run: |
          ls
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          # echo "name=FILELIST::$(printf '"%s" ' *.md)" >> $GITHUB_ENV
          # for f in {{ env.FILELIST }}; do 
      - uses: docker://pandoc/latex:2.9
        with:
            args: --output=output/result.html README.md
      - uses: actions/download-artifact@v2
        with:
          name: output
          path: output   
      - name: Display structure of downloaded files
        run: ls -R
          
          

