name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "foo" > input.txt  
      - uses: docker://pandoc/core:2.9
        with:
          args: |>  
            --standalone
            --output=index.html
            input.txt
