name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
        - run: |
            dir
            echo "foo" > input.txt 
            dir
        - uses: docker://pandoc/core:2.9
          with:
            args: |
              -v 
      
